# Funding Attribution
#
# This project directs financial support to Emsenn, whose discussions
# and insights were invaluable to its development.
#
# Please consider supporting them directly.

ko_fi: emsenn
